### ISSUE TITLE
Auto Close Application issue

### ISSUE THREAD

**Issue by Volvein** [Audio4Linux/JDSP4Linux#179] opened 2023-12-26 11:57 UTC
when i run next audio/video then its auto closing application. i have got this issue in linux fedora 39.

**Comment by WAPEETY** [comment] 2024-01-11 16:09
same here on Arch

**Comment by ThePBone** [comment] 2024-01-11 18:15
This bug is a duplicate of #155.

The scheduler kills the processing thread that is created by PipeWire because it has exceeded a certain threshold of allowed processing time.

You might be able to fix this by granting realtime privileges:
> Solved by installing realtime-privileges and adding the user to the group realtime.

**Closed by ThePBone** 2024-01-11 18:15 UTC
