### ISSUE TITLE
using nl80211

### ISSUE THREAD

**Issue by s-rs** [Audio4Linux/JDSP4Linux#129] opened 2023-06-22 16:45 UTC
[   20.336769] warning: `jamesdsp' uses wireless extensions which will stop working for Wi-Fi 7 hardware; use nl80211

this error pops up in kernel logs

**Comment by ThePBone** [comment] 2023-06-22 16:51
This warning appears to be caused by Qt (UI toolkit) and not by JamesDSP itself.
JDSP doesn't use wireless extensions, so this is a Qt bug. 
See also here: https://github.com/nextcloud/desktop/issues/5646#issuecomment-1579354538

[QTBUG-114336](https://bugreports.qt.io/browse/QTBUG-114336) has been filed, it will probably be fixed in a future Qt update.

**Closed by ThePBone** 2023-06-22 16:51 UTC

**Comment by s-rs** [comment] 2023-06-23 01:53
alright, thanks for your work
